[package]
name = "gundam"
version = "0.1.0"
authors = ["mario incandenza"]

[dependencies]
darwin-rs = { path = "../darwin-rs" }
pssm = { path = "../rust-pssm" }
bio = "*"
rand = "*"
ndarray = "*"
jobsteal = "*"
